# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Golang CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
      - name: Format
        run: go fmt ./...
      - name: Test
        run: go test ./...
      - name: go lint
        run: go vet ./...
      - name: Build
        run: go build cmt/main.go
